
// import './globals.css'
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import Provider from '../Provider';
// import ThemeButton from '@/components/Theme'
// import { SaasProvider } from '@saas-ui/react';
// import { AuthProvider } from '@saas-ui/auth';
// import { Layout } from './components/layout';
// import theme from './theme';
// import { AppProps } from 'next/app';
// import { Box, SkipNavContent, SkipNavLink } from '@chakra-ui/react';
// import { AnnouncementBanner } from './components/announcement-banner';
// import { Header } from './components/layout/header';
// import { Footer } from './components/layout/footer';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }



// export default function RootLayout({
//     children,
// }: {
//     children: AppProps
// }) {
//     return (
//         <html lang="en">
//             <body className={inter.className}>
//                 <SaasProvider theme={theme}>
//                     <AuthProvider>
//                         <Box>
//                             <SkipNavLink>Skip to content</SkipNavLink>
//                             <AnnouncementBanner {...announcementProps} />
//                             <Header {...headerProps} />
//                             <Box as="main">
//                                 <SkipNavContent />
//                                 {children}
//                             </Box>
//                             <Footer {...footerProps} />
//                         </Box>
//                     </AuthProvider>
//                 </SaasProvider>
//             </body>
//         </html>
//     )
// }
